# Generated by Django 5.1.3 on 2024-11-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.CharField(default="", max_length=20),
        ),
    ]
