# Generated by Django 5.1.3 on 2024-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_profile",
            "0002_alter_userprofile_age_alter_userprofile_height_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="calories_intake",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="exercise_duration",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sleep_hours",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="water_intake",
            field=models.CharField(default="", max_length=20),
        ),
    ]
